server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clientmicro
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    show-sql: true
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

