server:
  port: 8002
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: imagemicro
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

